# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntag', '0002_auto_20170930_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tag'),
        ),
    ]
