# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntag', '0005_auto_20170930_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='image',
            new_name='image_bad',
        ),
        migrations.AddField(
            model_name='tag',
            name='image_common',
            field=models.ImageField(blank=True, null=True, upload_to='tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='image_good',
            field=models.ImageField(blank=True, null=True, upload_to='tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='image_pychart',
            field=models.ImageField(blank=True, null=True, upload_to='tag'),
        ),
    ]
