# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntag', '0006_auto_20170930_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='image_bad',
            new_name='bad_words',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='image_common',
            new_name='common_words',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='image_good',
            new_name='good_words',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='image_pychart',
            new_name='piechart',
        ),
    ]
